Feature: CSRF Protection Validation

  Background:
    * url 'http://localhost:8080'
    * def username = 'testuser'
    * def sessionId = 'test-session-123'
    * def userAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    
    # In real scenario, this would be generated by token-issuing service
    # For testing, use the CsrfTokenGenerator utility
    * def validToken = 'eyJhbGciOiJSUzI1NiJ9...' # Replace with actual token

  Scenario: GET request should not require CSRF token
    Given path '/api/resource'
    And header idcs_remote_user = username
    And header idcs_session_id = sessionId
    And header User-Agent = userAgent
    When method GET
    Then status 200 or status 404
    # Should not be rejected with 403

  Scenario: POST request without CSRF token should return 403
    Given path '/api/resource'
    And header idcs_remote_user = username
    And header idcs_session_id = sessionId
    And header User-Agent = userAgent
    And header Cookie = 'session=test'
    And request { "data": "test" }
    When method POST
    Then status 403
    And match response.error == 'missing_csrf_token'
    And match response.message contains 'CSRF token is required'

  Scenario: POST request with valid CSRF token should proceed
    Given path '/api/resource'
    And header X-CSRF-Token = validToken
    And header idcs_remote_user = username
    And header idcs_session_id = sessionId
    And header User-Agent = userAgent
    And header Cookie = 'session=test'
    And header x-chainId = 'chain-001'
    And header x-hdp-hotel-id = 'hotel-123'
    And request { "data": "test" }
    When method POST
    Then status 200 or status 404
    # Should not be rejected with 403

  Scenario: Service-to-service call should bypass CSRF
    Given path '/api/resource'
    And header Authorization = 'Bearer s2s-token-xyz'
    And request { "data": "test" }
    When method POST
    Then status 200 or status 404
    # Should not be rejected with 403

  Scenario: PUT request without CSRF token should return 403
    Given path '/api/resource/123'
    And header idcs_remote_user = username
    And header idcs_session_id = sessionId
    And header User-Agent = userAgent
    And header Cookie = 'session=test'
    And request { "data": "updated" }
    When method PUT
    Then status 403
    And match response.error == 'missing_csrf_token'

  Scenario: DELETE request without CSRF token should return 403
    Given path '/api/resource/123'
    And header idcs_remote_user = username
    And header idcs_session_id = sessionId
    And header User-Agent = userAgent
    And header Cookie = 'session=test'
    When method DELETE
    Then status 403
    And match response.error == 'missing_csrf_token'

  Scenario: PATCH request without CSRF token should return 403
    Given path '/api/resource/123'
    And header idcs_remote_user = username
    And header idcs_session_id = sessionId
    And header User-Agent = userAgent
    And header Cookie = 'session=test'
    And request { "data": "patched" }
    When method PATCH
    Then status 403
    And match response.error == 'missing_csrf_token'

  Scenario: OPTIONS request should bypass CSRF
    Given path '/api/resource'
    When method OPTIONS
    Then status 200 or status 404
    # Should not be rejected with 403

  Scenario: POST with expired token should return 403
    Given path '/api/resource'
    And header X-CSRF-Token = 'expired-token-here'
    And header idcs_remote_user = username
    And header idcs_session_id = sessionId
    And header User-Agent = userAgent
    And header Cookie = 'session=test'
    And request { "data": "test" }
    When method POST
    Then status 403
    And match response.error == 'invalid_csrf_token'

  Scenario: POST with token but missing username header should return 403
    Given path '/api/resource'
    And header X-CSRF-Token = validToken
    And header idcs_session_id = sessionId
    And header User-Agent = userAgent
    And header Cookie = 'session=test'
    And request { "data": "test" }
    When method POST
    Then status 403
    And match response.error == 'missing_user_header'

  Scenario: POST with token but missing session header should return 403
    Given path '/api/resource'
    And header X-CSRF-Token = validToken
    And header idcs_remote_user = username
    And header User-Agent = userAgent
    And header Cookie = 'session=test'
    And request { "data": "test" }
    When method POST
    Then status 403
    And match response.error == 'missing_session_header'

  Scenario: Verify all custom headers are preserved
    Given path '/api/echo'
    And header X-CSRF-Token = validToken
    And header idcs_remote_user = username
    And header idcs_session_id = sessionId
    And header User-Agent = userAgent
    And header Cookie = 'session=test'
    And header x-chainId = 'chain-001'
    And header x-hdp-hotel-id = 'hotel-123'
    And header Custom-Header = 'custom-value'
    And request { "data": "test" }
    When method POST
    # Assuming backend echoes headers back
    Then match responseHeaders contains { 'x-chainId': ['chain-001'] }
    And match responseHeaders contains { 'x-hdp-hotel-id': ['hotel-123'] }
